<?php

namespace Modules\Ledger\Enums;

enum PaymentMethods: string
{
    case CASH = 'CASH';

    case QRIS_BCA = 'QRIS_BCA';

    case QRIS_BRI = 'QRIS_BRI';

    case QRIS_GPN = 'QRIS_GPN';

    case QRIS_SHOOPEPAY = 'QRIS_SHOOPEPAY';

    case QRIS_GOPAY = 'QRIS_GOPAY';

    case QRIS_OVO = 'QRIS_OVO';

    case QRIS_DANA = 'QRIS_DANA';

    case QRIS_JENIUS = 'QRIS_JENIUS';

    case QRIS_LINKAJA = 'QRIS_LINKAJA';

    case PAY_LATER_AKULAKU = 'PAY_LATER_AKULAKU';

    case PAY_LATER_KREDIVO = 'PAY_LATER_KREDIVO';

    case VIRTUAL_ACCOUNT_BCA = 'VIRTUAL_ACCOUNT_BCA';

    case VIRTUAL_ACCOUNT_MANDIRI = 'VIRTUAL_ACCOUNT_MANDIRI';

    case VIRTUAL_ACCOUNT_PERMATA = 'VIRTUAL_ACCOUNT_PERMATA';

    case VIRTUAL_ACCOUNT_BPD_BALI = 'VIRTUAL_ACCOUNT_BPD_BALI';

    case VIRTUAL_ACCOUNT_ARTHAGRAHA = 'VIRTUAL_ACCOUNT_ARTHAGRAHA';

    case VIRTUAL_ACCOUNT_BNI = 'VIRTUAL_ACCOUNT_BNI';

    case VIRTUAL_ACCOUNT_BRI = 'VIRTUAL_ACCOUNT_BRI';

    case VIRTUAL_ACCOUNT_MUAMALAT = 'VIRTUAL_ACCOUNT_MUAMALAT';

    case VIRTUAL_ACCOUNT_BSI = 'VIRTUAL_ACCOUNT_BSI';

    case BANK_TRANSFER_BCA = 'BANK_TRANSFER_BCA';

    case BANK_TRANSFER_MANDIRI = 'BANK_TRANSFER_MANDIRI';

    case BANK_TRANSFER_ANZ = 'BANK_TRANSFER_ANZ';

    case BANK_TRANSFER_STANDARDCARTERED = 'BANK_TRANSFER_STANDARDCARTERED';

    case CREDIT_CARD_MASTERCARD = 'CREDIT_CARD_MASTERCARD';

    case CREDIT_CARD_VISA = 'CREDIT_CARD_VISA';

    case CREDIT_CARD_JCB = 'CREDIT_CARD_JCB';

    case DEBIT_CARD = 'DEBIT_CARD';

    case DIRECT_DEBIT_BCA = 'DIRECT_DEBIT_BCA';

    case DIRECT_DEBIT_BRI = 'DIRECT_DEBIT_BRI';

    case DIRECT_DEBIT_BNI = 'DIRECT_DEBIT_BNI';

    case DIRECT_DEBIT_CIMB = 'DIRECT_DEBIT_CIMB';

    case DIRECT_DEBIT_BTN = 'DIRECT_DEBIT_BTN';

    case DIRECT_DEBIT_GPN = 'DIRECT_DEBIT_GPN';

    case E_WALLET_LINKAJA = 'E_WALLET_LINKAJA';

    case E_WALLET_GOPAY = 'E_WALLET_GOPAY';

    case E_WALLET_OVO = 'E_WALLET_OVO';

    case E_WALLET_DANA = 'E_WALLET_DANA';

    case E_WALLET_WECHATPAY = 'E_WALLET_WECHATPAY';

    case E_WALLET_SHOOPEPAY = 'E_WALLET_SHOOPEPAY';

    case E_WALLET_ALIPAY = 'E_WALLET_ALIPAY';

    case E_WALLET_DOKU = 'E_WALLET_DOKU';

    case E_WALLET_INSTAPAY = 'E_WALLET_INSTAPAY';

    case E_WALLET_PAYNOW = 'E_WALLET_PAYNOW';

    case E_WALLET_DUITNOW = 'E_WALLET_DUITNOW';

    case E_WALLET_PROMPTPAY = 'E_WALLET_PROMPTPAY';

    case E_WALLET_FPS = 'E_WALLET_FPS';

    case E_WALLET_VIETTEL_MONEY = 'E_WALLET_VIETTEL_MONEY';

    case E_WALLET_TOSS = 'E_WALLET_TOSS';

    case PAYPAL = 'PAYPAL';

    case PAYONER = 'PAYONER';

    case CHEQUE = 'CHEQUE';

    case GIRO = 'GIRO';

    case BILYET_GIRO = 'BILYET_GIRO';

    case CONVINIENT_STORE_INDOMARET = 'CONVINIENT_STORE_INDOMARET';

    case CONVINIENT_STORE_ALFAMART = 'CONVINIENT_STORE_ALFAMART';

    case CONVINIENT_STORE_DANDAN = 'CONVINIENT_STORE_DANDAN';

    case CONVINIENT_STORE_LAWSON = 'CONVINIENT_STORE_LAWSON';


}
